# Generated by Django 4.2.8 on 2023-12-20 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('newsChannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newschannels')),
            ],
        ),
        migrations.CreateModel(
            name='NewsHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('post', models.TextField()),
                ('country', models.CharField(max_length=30)),
                ('extraNews', models.BooleanField()),
                ('newsSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newssection')),
            ],
        ),
    ]
